spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/SVMDB
spring.datasource.username=postgres
spring.datasource.password=Santanu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=5000