spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-quiet-block-aouq957f-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_p6jMt7NwnZAa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.ai.google.genai.api-key=AIzaSyDnFcdf9O9zEdJ4A9olikkI7AursfANTmY
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview